---
title: "Preliminary Models"
author: "Sebastian Rojas Cabal"
date: "7/26/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prelim, message = FALSE, echo= FALSE}
library(tidyverse)
library(stargazer)
library(lmtest)
library(sandwich)
library(lfe)
library(plm)
```

```{r loading_data, echo=FALSE, message = FALSE}
nonprofits_analysis <- read_csv("/Users/srojascabal/Desktop/000_f990_data/analytical_sample_220726.csv",
     col_types = cols(
      ein = col_character(),
      tax_year = col_character(),
      anti_lgbtq = col_double(),
      anti_factor = col_factor(),
      rtrn_state = col_factor(),
      totalXpns_2013_100k = col_double(),
      frgnXpns_2013_100k = col_double(),
      log_frgnXpns_2013_100k = col_double(),
      propFrgnXpns_2013_100k = col_double(),
      yearMrgEq_rtrn = col_double(),
      ind_yearMrgEq_rtrn = col_double(),
      college_educ_over_25 = col_double(),
      frgn_born = col_double(),
      state_population = col_double(),
      exempt_orgs = col_double(),
      rel_orgs = col_double(),
      gdp_state_2012 = col_double(),
      gdp_state_2012_100k = col_double(),
      gov_party = col_character(),
      gov_republican = col_double()
      )) %>%
  mutate(
    winsor_totalXpns_2012_99 = Winsorize(totalXpns_2012_100k, probs=c(0.00, 0.99)),
    winsor_totalXpns_2012_95 = Winsorize(totalXpns_2012_100k, probs=c(0.00, 0.95)),
    log_gdp_2012 = log(gdp_state_2012),
    log_gdp_2012_100k = log(gdp_state_2012_100k),
    log_frgnXpns_2013_100k = log(frgnXpns_2013_100k+1),
    log_totalXpns_2013_100k = log(totalXpns_2013_100k+1),
    log_rel_orgs = log(rel_orgs +1),
    log_exempt_orgs = log(exempt_orgs+1)
  )

#   na_df_total <- nonprofits_analysis %>%
#     summarise(across(everything(), ~ sum(is.na(.))))
```

```{r descriptives, results = "asis", message = FALSE, echo= FALSE}
stargazer(as.data.frame(nonprofits_analysis), type = 'latex')
```

## Models without Fixed Effects Robust Standard Errors
```{r models, echo=FALSE}
# Logged Foreign Expenses, no controls
model1 <- lm(log_frgnXpns_2013_100k ~ anti_lgbtq,
             nonprofits_analysis)

# Foreign Expenses, controls + interaction
model2 <- lm(log_frgnXpns_2013_100k ~ anti_lgbtq + 
               anti_lgbtq*ind_yearMrgEq_rtrn +
               gov_republican +
               state_population +
               frgn_born +
               college_educ_over_25 +
               log_gdp_2012 + 
               ind_yearMrgEq_rtrn + 
               log_exempt_orgs + 
               log_rel_orgs + 
               log_totalXpns_2013_100k,
             nonprofits_analysis)

# % of Total Expenditures, no controls
model3 <- lm(propFrgnXpns_2013_100k ~ anti_lgbtq,
             nonprofits_analysis)

# % of Total Expenditures, controls + interaction
model4 <- lm(propFrgnXpns_2013_100k ~ anti_lgbtq +
                anti_lgbtq*ind_yearMrgEq_rtrn +
                gov_republican +
                state_population +
                frgn_born +
                college_educ_over_25 +
                log_gdp_2012 +
                ind_yearMrgEq_rtrn +
                log_exempt_orgs +
                log_rel_orgs,
              nonprofits_analysis)
```

```{r model_results_TotalExpenses, results = "asis", echo=FALSE}
stargazer(model1, model2, type = 'latex',
          title = "Foreign Expenditures by Anti-LGBTQ Nonprofits, 2013-2019",
          covariate.labels = c("Anti-LGBTQ Nonprofit",
                               "Republican Governor",
                               "State population",
                               "Foreign-Born Population in State",
                                "College-Educated Population in State",
                               "State real GDP (Log)",
                               "Marriage Equality Passed",
                               "Nonprofit Activity in State (Log)",
                               "Religiosity of State Population (Log)",
                               "Org's Total Expenses (Log)",
                               "Interaction:Anti/Marriage Eq"),
          dep.var.labels   = c("Log of Total Foreign Expenses"),
          single.row = TRUE)
```

```{r model_results_PctnExpenses, results = "asis", echo=FALSE}
stargazer(model3, model4, type = 'latex',
           title = "Foreign Expenses as a Proportion of Total Expenses  by Anti-LGBTQ Nonprofits, 2013-2020",
           covariate.labels = c("Anti-LGBTQ Nonprofit",
                                "Republican Governor",
                                "State population",
                               "Foreign-Born Population in State",
                                "College-Educated Population in State",
                                "State real GDP (Log)",
                                "Marriage Equality Passed",
                                "Nonprofit Activity in State (Log)",
                                "Religiosity of State Population (Log)",
                               "Interaction:Anti/Marriage Eq"),
           dep.var.labels   = c("Foreign Expenses as Proportion of Total Expenses"),
           single.row = TRUE)
```

## Models with Fixed Effects and Robust Standard Errors
```{r models_FE, echo=FALSE}
anti_nonprofits <- nonprofits_analysis %>%
  filter(anti_lgbtq == 1)

# Logged Foreign Expenses, no controls
model1_fe <- felm(log_frgnXpns_2013_100k ~ anti_lgbtq |
                  rtrn_state + ein |
                  0 | 
                  rtrn_state + ein,
                  anti_nonprofits)

# Foreign Expenses, controls
model2_fe <- felm(log_frgnXpns_2013_100k ~ anti_lgbtq + gov_republican + log_gdp_2012 + ind_yearMrgEq_rtrn + log_exempt_orgs + log_rel_orgs + log_totalXpns_2013_100k |
                rtrn_state + ein |
                0 | 
                rtrn_state + ein,
                anti_nonprofits)

# % of Total Expenditures, no controls
model3_fe <- felm(propFrgnXpns_2013_100k ~ anti_lgbtq |
                  rtrn_state + ein |
                  0 | 
                  rtrn_state + ein,
                  anti_nonprofits)

# % of Total Expenditures, controls
model4_fe <- felm(propFrgnXpns_2013_100k ~ anti_lgbtq + gov_republican + log_gdp_2012 + ind_yearMrgEq_rtrn + log_exempt_orgs + log_rel_orgs + log_totalXpns_2013_100k |
                rtrn_state + ein |
                0 | 
                rtrn_state + ein,
                anti_nonprofits)

```

# Total Foreign Expenses (Log), no controls
```{r modelFE_results_TotalExpenses, echo=FALSE}
summary(model1_fe)
```

# Total Foreign Expenses (Log), with  controls
```{r modelFE_results_TotalExpenses2, echo=FALSE}
summary(model2_fe)
```

# % of Total Expenses, no controls
```{r modelFE_results_PctnExpenses, echo=FALSE}
summary(model3_fe)
```

# % of Total Expenses, with  controls
```{r modelFE_results_PctnExpenses2, echo=FALSE}
summary(model4_fe)
```
